# ls-lint configuration
# Explicit allowlist - only these files/directories permitted at root

ls:
  # Allowed root files
  .config.ts: regex:eslint | regex:prettier | regex:stylelint | regex:vite
  .json: regex:package | regex:package-lock | regex:tsconfig | regex:tsconfig\.tooling | regex:knip
  .html: regex:index
  .md: regex:README | regex:CLAUDE
  .yml: regex:\.ls-lint
  -versions: regex:\.tool

  # Block any other extensions at root
  .*: regex:$

  # Allowed root directories
  .dir: regex:\.claude | regex:\.git | regex:dist | regex:docs | regex:eslint-rules | regex:node_modules | regex:public | regex:scripts | regex:src | regex:src-tauri

  # .claude directory - only officially supported Anthropic files
  .claude:
    .json: regex:settings | regex:settings\.local | regex:\.mcp
    .md: regex:CLAUDE
    .*: regex:$
    .dir: regex:\.claude | regex:hooks | regex:commands | regex:agents | regex:skills

  # .claude/skills - kebab-case directories for skill definitions
  .claude/skills:
    .*: regex:$
    .dir: kebab-case

  # .claude/skills/* - SKILL.md files only in each skill directory
  .claude/skills/*:
    .md: regex:SKILL
    .*: regex:$
    .dir: kebab-case

  # .claude/hooks - camelCase JS files only, no subdirectories
  .claude/hooks:
    .js: camelCase
    .*: regex:$
    .dir: regex:hooks

  # .claude/commands - kebab-case markdown files for slash commands
  .claude/commands:
    .md: kebab-case
    .*: regex:$
    .dir: regex:commands

  # .claude/agents - kebab-case markdown files for agent definitions
  .claude/agents:
    .md: kebab-case
    .*: regex:$
    .dir: regex:agents

  # docs - SCREAMING_SNAKE_CASE markdown files only
  docs:
    .md: SCREAMING_SNAKE_CASE
    .*: regex:$
    .dir: regex:docs

  # eslint-rules - kebab-case TS files only, no subdirectories
  eslint-rules:
    .ts: kebab-case
    .*: regex:$
    .dir: regex:eslint-rules

  # public - favicon files only, no subdirectories
  public:
    .ico: kebab-case
    .svg: kebab-case
    .png: kebab-case
    .*: regex:$
    .dir: regex:public

  # scripts - camelCase JS files, plus hooks subdirectory
  scripts:
    .js: camelCase
    .*: regex:$
    .dir: regex:scripts | regex:hooks

  # scripts/hooks - camelCase JS files for git hooks
  scripts/hooks:
    .js: camelCase
    .*: regex:$
    .dir: regex:hooks

  # src/assets - only fonts and images directories, no files at root
  src/assets:
    .*: regex:$
    .dir: regex:assets | regex:fonts | regex:images

  # src/assets/fonts - font files only, no subdirectories
  src/assets/fonts:
    .ttf: regex:.+
    .TTF: regex:.+
    .otf: regex:.+
    .OTF: regex:.+
    .woff: regex:.+
    .WOFF: regex:.+
    .woff2: regex:.+
    .WOFF2: regex:.+
    .*: regex:$
    .dir: regex:fonts

  # src/assets/images - camelCase image files only, no subdirectories
  # Using regex instead of camelCase to allow acronyms (e.g., itmNVGoggles, itmIDCard)
  src/assets/images:
    .png: regex:[a-z][a-zA-Z0-9]*
    .jpg: regex:[a-z][a-zA-Z0-9]*
    .jpeg: regex:[a-z][a-zA-Z0-9]*
    .svg: regex:[a-z][a-zA-Z0-9]*
    .gif: regex:[a-z][a-zA-Z0-9]*
    .webp: regex:[a-z][a-zA-Z0-9]*
    .*: regex:$
    .dir: regex:images

  # src root files - only index.tsx and index.css allowed
  src:
    .tsx: regex:index
    .css: regex:index
    .*: regex:$
    .dir: regex:src | regex:@types | regex:assets | regex:constants | regex:data | regex:ecs | regex:game | regex:hooks | regex:renderer | regex:stores | regex:types | regex:ui | regex:utils

  # src/@types - kebab-case declaration files (.d.ts) only, no subdirectories
  src/@types:
    .d.ts: kebab-case
    .*: regex:$
    .dir: regex:@types

  # src/constants - domain-specific .ts files only, no subdirectories
  src/constants:
    .ts: regex:character|conditions|status|medical|equipment|inventory|crafting|combat|movement|stealth|scavenging|map|locations|weather|time|factions|vehicles|input|ui|audio|assets|save|settings|primitives
    .*: regex:$
    .dir: regex:constants

  # src/data - camelCase .json files only (no .ts), no subdirectories
  src/data:
    .json: camelCase
    .*: regex:$
    .dir: regex:data

  # src/hooks - .ts files starting with "use" only, no subdirectories
  src/hooks:
    .ts: regex:use[A-Z][a-zA-Z0-9]*
    .*: regex:$
    .dir: regex:hooks

  # src/ui - React UI components (renamed from components/)
  src/ui:
    .tsx: PascalCase
    .module.css: PascalCase
    .ts: regex:index
    .*: regex:$
    .dir: regex:ui

  # src/ecs - Entity Component System
  src/ecs:
    .ts: regex:world
    .*: regex:$
    .dir: regex:ecs | regex:components | regex:systems | regex:entities | regex:queries

  # src/ecs/components - camelCase files ending with Component.ts
  src/ecs/components:
    .ts: regex:[a-z][a-zA-Z0-9]*Component
    .*: regex:$
    .dir: regex:components

  # src/ecs/systems - camelCase files ending with System.ts
  src/ecs/systems:
    .ts: regex:[a-z][a-zA-Z0-9]*System
    .*: regex:$
    .dir: regex:systems

  # src/ecs/entities - camelCase files ending with Entity.ts
  src/ecs/entities:
    .ts: regex:[a-z][a-zA-Z0-9]*Entity
    .*: regex:$
    .dir: regex:entities

  # src/ecs/queries - camelCase files ending with Queries.ts
  src/ecs/queries:
    .ts: regex:[a-z][a-zA-Z0-9]*Queries
    .*: regex:$
    .dir: regex:queries

  # src/renderer - PixiJS rendering layer
  src/renderer:
    .*: regex:$
    .dir: regex:renderer | regex:core | regex:layers | regex:sprites | regex:shaders

  # src/renderer/core - camelCase .ts files
  src/renderer/core:
    .ts: camelCase
    .*: regex:$
    .dir: regex:core

  # src/renderer/layers - camelCase files ending with Layer.ts
  src/renderer/layers:
    .ts: regex:[a-z][a-zA-Z0-9]*Layer
    .*: regex:$
    .dir: regex:layers

  # src/renderer/sprites - camelCase files ending with Sprite.ts
  src/renderer/sprites:
    .ts: regex:[a-z][a-zA-Z0-9]*Sprite
    .*: regex:$
    .dir: regex:sprites

  # src/renderer/shaders - camelCase shader files
  src/renderer/shaders:
    .frag: camelCase
    .vert: camelCase
    .*: regex:$
    .dir: regex:shaders

  # src/game - Game coordination layer
  src/game:
    .*: regex:$
    .dir: regex:game | regex:core | regex:input | regex:actions

  # src/game/core - camelCase .ts files
  src/game/core:
    .ts: camelCase
    .*: regex:$
    .dir: regex:core

  # src/game/input - camelCase files ending with Input.ts
  src/game/input:
    .ts: regex:[a-z][a-zA-Z0-9]*Input
    .*: regex:$
    .dir: regex:input

  # src/game/actions - camelCase files ending with Action.ts
  src/game/actions:
    .ts: regex:[a-z][a-zA-Z0-9]*Action
    .*: regex:$
    .dir: regex:actions

  # src/stores - camelCase files ending with Store.ts, plus slices subdirectory
  src/stores:
    .ts: regex:[a-z][a-zA-Z0-9]*Store
    .*: regex:$
    .dir: regex:stores | regex:slices

  # src/stores/slices - camelCase files ending with Slice.ts, no subdirectories
  src/stores/slices:
    .ts: regex:[a-z][a-zA-Z0-9]*Slice
    .*: regex:$
    .dir: regex:slices

  # src/types - domain-specific .ts files only, no subdirectories
  src/types:
    .ts: regex:character|conditions|status|medical|equipment|inventory|crafting|combat|movement|stealth|scavenging|map|locations|weather|time|factions|vehicles|input|ui|audio|assets|save|settings|primitives
    .*: regex:$
    .dir: regex:types

ignore:
  # Ignore subdirectory contents - rules added incrementally
  - .git
  - dist
  - node_modules
  - src/utils
  - src-tauri
