# ls-lint configuration
# Explicit allowlist - only these files/directories permitted at root

ls:
  # Allowed root files
  .config.ts: regex:eslint | regex:prettier | regex:stylelint | regex:vite
  .json: regex:package | regex:package-lock | regex:tsconfig | regex:tsconfig\.tooling
  .html: regex:index
  .md: regex:README
  .yml: regex:\.ls-lint

  # Block any other extensions at root
  .*: regex:$

  # Allowed root directories
  .dir: regex:\.claude | regex:dist | regex:docs | regex:eslint-rules | regex:node_modules | regex:public | regex:scripts | regex:src

  # .claude directory - only officially supported Anthropic files
  .claude:
    .json: regex:settings | regex:settings\.local | regex:\.mcp
    .md: regex:CLAUDE
    .*: regex:$
    .dir: regex:\.claude | regex:hooks | regex:agents

  # .claude/hooks - camelCase JS files only, no subdirectories
  .claude/hooks:
    .js: camelCase
    .*: regex:$
    .dir: regex:hooks

  # .claude/agents - will be configured when used
  .claude/agents:
    .*: regex:$
    .dir: regex:agents

  # docs - SCREAMING_SNAKE_CASE markdown files only
  docs:
    .md: SCREAMING_SNAKE_CASE
    .*: regex:$
    .dir: regex:docs

  # eslint-rules - kebab-case TS files only, no subdirectories
  eslint-rules:
    .ts: kebab-case
    .*: regex:$
    .dir: regex:eslint-rules

  # public - favicon files only, no subdirectories
  public:
    .ico: kebab-case
    .svg: kebab-case
    .png: kebab-case
    .*: regex:$
    .dir: regex:public

ignore:
  # Ignore subdirectory contents - rules added incrementally
  - dist
  - node_modules
  - scripts
  - src
