extends Node

class_name ActionTypes

const GAME_LOG_APPEND = "GAME_LOG_APPEND"

const CAMERA_SET_POSITION = "CAMERA_SET_POSITION"
const CAMERA_SET_OFFSET = "CAMERA_SET_OFFSET"

const HEX_SELECT_SET_INDEX = "HEX_SELECT_SET_INDEX"
