import type { SlotType } from '../types/inventory';

export const SLOT_TYPES: SlotType[] = [
  'helmet',
  'eyes',
  'face',
  'neck',
  'backpack',
  'coat',
  'vest',
  'shirt',
  'rightShoulder',
  'leftShoulder',
  'rightGlove',
  'leftGlove',
  'rightRing',
  'leftRing',
  'rightHolding',
  'leftHolding',
  'pouch',
  'pants',
  'rightShoe',
  'leftShoe',
];

export const SLOT_LABELS: Record<SlotType, string> = {
  helmet: 'Helmet',
  eyes: 'Eyes',
  face: 'Face',
  neck: 'Neck',
  backpack: 'Backpack',
  coat: 'Coat',
  vest: 'Vest',
  shirt: 'Shirt',
  rightShoulder: 'Right Shoulder',
  leftShoulder: 'Left Shoulder',
  rightGlove: 'Right Glove',
  leftGlove: 'Left Glove',
  rightRing: 'Right Ring',
  leftRing: 'Left Ring',
  rightHolding: 'Right Holding',
  leftHolding: 'Left Holding',
  pouch: 'Pouch',
  pants: 'Pants',
  rightShoe: 'Right Shoe',
  leftShoe: 'Left Shoe',
};

export const SLOT_ICONS: Record<SlotType, string> = {
  helmet: '⛑',
  eyes: '👓',
  face: '😷',
  neck: '🧣',
  backpack: '🎒',
  coat: '🧥',
  vest: '🦺',
  shirt: '👕',
  rightShoulder: '⬛',
  leftShoulder: '⬛',
  rightGlove: '🧤',
  leftGlove: '🧤',
  rightRing: '💍',
  leftRing: '💍',
  rightHolding: '✋',
  leftHolding: '✋',
  pouch: '👝',
  pants: '👖',
  rightShoe: '👟',
  leftShoe: '👟',
};

export const SLOT_DESCRIPTIONS: Record<SlotType, string> = {
  helmet: 'Protects your head from impacts and environmental hazards.',
  eyes: 'Shields your eyes from debris, bright light, or harmful particles.',
  face: 'Covers your face for protection or filtering air.',
  neck: 'Provides warmth or protection for your neck area.',
  backpack: 'Your main storage for carrying items and supplies.',
  coat: 'Outer layer providing warmth and weather protection.',
  vest: 'Tactical or protective vest worn over clothing.',
  shirt: 'Base layer clothing for your torso.',
  rightShoulder: 'Attachment point for shoulder-mounted gear.',
  leftShoulder: 'Attachment point for shoulder-mounted gear.',
  rightGlove: 'Protects your right hand and improves grip.',
  leftGlove: 'Protects your left hand and improves grip.',
  rightRing: 'Accessory slot for your right hand.',
  leftRing: 'Accessory slot for your left hand.',
  rightHolding: 'What you hold in your right hand.',
  leftHolding: 'What you hold in your left hand.',
  pouch: 'Small container for quick-access items.',
  pants: 'Lower body clothing with potential pocket storage.',
  rightShoe: 'Footwear for your right foot.',
  leftShoe: 'Footwear for your left foot.',
};
